### PR TITLE
git stash command

### PR DESCRIPTION
**Pull request by thojansen**
i would like to add some information on [git stash](https://git-scm.com/book/en/v1/Git-Tools-Stashing), because it is a very helpful command in case stuff needs to be fixed while in the middle of s.th. else on the same branch

4295488113_6c60aa41c6

### CODE REVIEW

**Comment by matz3** [comment]
Looks good :+1:
You may add "fixes #27" to the commit message to automatically close the related issue.

**Comment by geekflyer** [comment]
:sake:

**Comment by casche** [comment]
@thojansen you were away from your desk so I'm going to merge this for you

**Comment by thojansen** [comment]
:+1: thanks @casche

**Pull request merged**
