### PR TITLE
Added a GitHub blog post

### PR DESCRIPTION
**Pull request by casche**
Looks like a great blog post on how to remove anything in Git. @githubstudent I'd like to add this link.

### CODE REVIEW

**Comment by githubteacher** [comment]
@casche can you follow the steps above to resolve this conflict :smile:

**Comment by casche** [comment]
hey @githubteacher what's with this error? :cry: 

`
$ git checkout -b casche-useful-links origin/casche-useful-links
fatal: A branch named 'casche-useful-links' already exists.
`

**Comment by casche** [comment]
hey thanks @githubteacher for resolving the conflict :+1:

**Comment by githubteacher** [comment]
@casche i went ahead and did the following:

```
git pull
git checkout  casche-useful-links
git merge useful-links
(resolved conflict)
git push
```

**Pull request merged**
